### ISSUE TITLE
Alternative Downloadoption to routinehub

### ISSUE THREAD

**Issue by lubiana** [net00-1/SW-DLT#12]
Routinehub has been down for me a lot recently, which means, that the update-check fails a lot and there is currently no way for me to install the shortcut, is there any alternative way to download the shortcut and to suppress the updatecheck?

I am still a big fan of your shortut and the great work you are doing.

**Comment by JDTm** [comment]
I fixed it for me: replaced the update URL in the dictionary (vars updateScript):

#data:text/html,<script>var rhGET = new XMLHttpRequest();rhGET.open("GET","https://myurl-must-be-valid/metadata (RID)/versions/latest", false);rhGET.send();document.write(rhGET.responseText);</script>

**Comment by lubiana** [comment]
I never got around to answer you, but thanks a lot, your advice helped me a lot to get this to work again

**Comment by net00-1** [comment]
Sorry for never replying, I could probably set up a simple endpoint in this github repo that acts as the source to get updates. I would need to test it first

**Comment by mrxoom1274** [comment]
That didn't work for me. I get a error message about a server not found. Do you have a solution for that ?

**Comment by denzelb127** [comment]
routine hub is screwing this shortcut over it doesn't work anymore

**Comment by net00-1** [comment]
Seems like pinging RH's API got much worse now. I'll push an update ASAP to use this repo as the update endpoint.

**Comment by net00-1** [comment]
Everything seems to be setup now! If you can't get the update through your existing copies due to slow RH servers, you can get it through [this link](https://www.icloud.com/shortcuts/951836e1710b45c2ad09d055af7eb12b), otherwise it will show up like a regular update.

From then on, it'll use the static API in the GitHub pages for this repo.

if anyone has other issues please feel free to open them.
