### ISSUE TITLE
File name dialogue from a-Shell mini

### ISSUE THREAD

**Issue by jeongyeonsbbl** [net00-1/SW-DLT#17]
After selecting video on the shortcut, a-Shell opens as expected, but then a dialogue asking you to input the file name appears. Naming it doesn’t work, nor does selecting one of the given options above the keyboard.

(i’m on ios16 rc so that might be a reason?)
![962BF8B9-FC45-4EE8-A2D4-77F932033A09](https://user-images.githubusercontent.com/113304317/189540122-66cc8281-6477-449e-b5a7-759bee790a43.png)
![AA0C1D47-73F0-4D36-82BF-5A0F96F1464D](https://user-images.githubusercontent.com/113304317/189540125-1d862457-aa51-4ae9-a65b-d2b91e25aa75.png)

**Comment by net00-1** [comment]
The script is supposed to pass data back to the shortcut, including the name of file to fetch.

Can you share the URL and options you used? Reinstalling the shortcut might work though.  Otherwise it could be an iOS 16 bug.

**Comment by net00-1** [comment]
I seem to have ran into the same error now. Looks like when the data is passed back to shortcuts, it gets automatically decoded.

This is bad since if the title contains "&" it gets interpreted as another dictionary key, and the whole thing can't be read properly. I encode the data to specifically avoid this, but Shortcuts for some reason decodes it when it shouldn't.

I'll test sticking to JSON data, and include the type of callback in it.

**Comment by net00-1** [comment]
I released a fix for this in the latest version. Will go ahead and close this if no one has this problem still
