### ISSUE TITLE
Ability to provide credentials

### ISSUE THREAD

**Issue by kriodoxis** [net00-1/SW-DLT#38]
When trying to download an Instgram video the following message appears:

![IMG_0638](https://github.com/net00-1/SW-DLT/assets/1276447/bd2c2c50-f5d8-4b36-8abf-0a7e56a4671a)

Provided the following link: https://www.instagram.com/reel/CybzFHyOcUo/?igshid=MzRlODBiNWFlZA==

**Comment by nReus** [comment]
I'd like to add on to this issue. It appears that the frontend takes links from Gallery-dl before G-DL begins downloading, which causes it to download from sources without the credentials I've manually provided to G-DL, resulting in 403 forbidden errors being downloaded as html files instead.

In my case, it was Pixiv that didn't work for all R18-tagged posts. And I don't think it would work on SW-DLT without major revision to how the frontend downloads galleries since Pixiv requires OAuth instead just providing username and password (G-DL uses an Android user-agent and Pixiv on Android browsers require OAuth afaik).

**Comment by net00-1** [comment]
For accounts that work with username & password, you can look in the [docs[(https://github.com/net00-1/SW-DLT/blob/master/Docs.md#authentication). There's a guide to setup a-shell to keep your credentials. 

I will keep this open to check for ways of other authentication types

**Comment by Cs0o** [comment]
As a newbie, do I have this directory structure set up correctly?
It keeps prompting "requires. authentication"


```
[~group]$ ls -Ra
.
..
.com.apple.mobile_container_manager.metadata.plist
.netrc
Library
SW_DLT.py
gallery-dl
yt-dlp
./Library:
.               Caches
..              Preferences
./Library/Caches:
.       ..
./Library/Preferences:
.
..
group.AsheKube.a-Shell.plist
./gallery-dl:
.               config.json
..
./yt-dlp:
.       ..      config

[~group]$ cat yt-dlp/config
--netrc
[~group]$ cat gallery-dl/config.json
{    "extractor": {        "twitter": {        
    "username": "$$$$$$",            "password":
 "$$$$$$"        }    }}
```

**Comment by net00-1** [comment]
Now much more convenient cookie-based authentication is available, you can check the updated docs about how to use it.
