### ISSUE TITLE
Codec problem, please change

### ISSUE THREAD

**Issue by BlobIsBack** [net00-1/SW-DLT#44]
It is impossible to download the video to photos app because of the codec, please change it to a codec like avc1

i tested with YouTube videos

**Comment by net00-1** [comment]
Hi, I'm sorry for ignoring these issues for a while. I'm just getting back into checking the shortcut and I pushed an update a few days ago to fix more breaking issues...

As for this issue, I replaced most of my custom format selector for yt-dlp's format sorting. I give priority for playable codecs (h264, aac) with `+codec:avc:m4a` as per their [documentation](https://github.com/yt-dlp/yt-dlp).

It works better on my side, but if anyone would like to test as well you can try this version, I'll push an update after a few more testing: 

https://www.icloud.com/shortcuts/20cd4fa25bca4ac29c6bbe0d68d0ac14

NOTE: this won't work if whatever website you are trying to download from doesn't offer the formats, that's why it's recommended to have an app like VLC.
